---
mysql_root_password: "sisopPenugasan123?"
http_host: "127.0.0.1"
http_conf: "laravel-local.conf"
http_port: "80"
github_repo_url: "https://gitlab.com/kuuhaku86/web-penugasan-individu"
working_directory: "/home/penugasan/tugas-ansible"